---
name: alpine docker image
on:
  schedule:
  - cron: '41 4 * * *'
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    branches:
    - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: kamailio-ci
  BUILDER_IMAGE: ghcr.io/sergey-safarov/kamailio-builder

jobs:
  # is required nightly build?
  # More info at https://stackoverflow.com/questions/63014786/how-to-schedule-a-github-actions-nightly-build-but-run-it-only-when-there-where
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: octokit/request-action@v2.x
        id: check_last_run
        with:
          route: GET /repos/{owner}/{repo}/actions/workflows/alpine.yml/runs?per_page=1&status=success
          owner: ${{ github.repository_owner }}
          repo: kamailio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show last execution info
        id: build_info
        run: |
          echo "Last daily build: ${{ fromJson(steps.check_last_run.outputs.data).workflow_runs[0].head_sha }}"
          if [ ${{ github.ref_name }} == "master" ]; then
            echo "image_tag=alpine-edge" >> "$GITHUB_OUTPUT"
          else
            echo "image_tag=alpine-latest" >> "$GITHUB_OUTPUT"
          fi

    outputs:
      last_sha: ${{ fromJson(steps.check_last_run.outputs.data).workflow_runs[0].head_sha }}
      build_image_tag: ${{ steps.build_info.outputs.image_tag }}

  build:
    name: Build sources
    needs: [check]
    if: needs.check.outputs.last_sha != github.sha
    strategy:
      fail-fast: false
      matrix:
        arch:
        - x86_64
        - aarch64
        include:
        # setting runner
        - runner: ubuntu-latest
        - runner: ubuntu-24.04-arm
          arch: aarch64
        # setting image used during build
        - build_image_tag: ${{ needs.check.outputs.build_image_tag }}
    runs-on: ${{ matrix.runner }}
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: print commit info
      id: init
      run: |
        git log -n 1
        pwd
        ls -la
        chown -R 1000:1000 ${{ github.workspace }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=pep440,pattern={{version}}
          type=pep440,pattern={{major}}.{{minor}}
          type=pep440,pattern={{major}}
          type=ref,event=branch
        flavor: |
          suffix=
          latest=auto

    - name: Docker meta "-alpine"
      id: meta-alpine
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=pep440,pattern={{version}}
          type=pep440,pattern={{major}}.{{minor}}
          type=pep440,pattern={{major}}
          type=ref,event=branch
        flavor: |
          suffix=-alpine
          latest=false

    - name: Docker meta "-debug"
      id: meta-debug
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=pep440,pattern={{version}}
          type=pep440,pattern={{major}}.{{minor}}
          type=pep440,pattern={{major}}
          type=ref,event=branch
        flavor: |
          suffix=-debug
          latest=false

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      if: "! contains(fromJson('[\"x86_64\", \"aarch64\"]'), matrix.arch)"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build sources
      uses: tj-actions/docker-run@v2
      with:
        image: ${{ env.BUILDER_IMAGE }}:${{ matrix.build_image_tag }}
        name: kamailio_builder
        options: --cap-add chown -v ${{ github.workspace }}:/usr/src/kamailio
        args: |
          /bin/sh -c "
          cd /usr/src/kamailio
          chown -R build:build *
          make cfg
          make -C pkg/kamailio apk
          abuild -C pkg/kamailio/alpine -r
          "

#    - name: Build builder image
#      uses: docker/build-push-action@v6
#      id: build
#      env:
#        DOCKER_BUILD_SUMMARY: false
#      with:
#        context: "{{defaultContext}}:rpm"
#        tags: ${{ steps.metadata.outputs.tags }}
#        labels: ${{ steps.metadata.outputs.labels }}
#        platforms: ${{ matrix.platform }}
#        build-args: |
#          base_image=${{ matrix.base_image }}
