---
name: build_rpm_nativily
'on':
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os:
        - centos-10
#        - rhel-10
#        - centos-9
#        - rhel-9
#        - centos-8
#        - rhel-8
        runner:
        - ubuntu-latest
#        - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: print latest_commit
      run: |
        echo ${{ github.sha }}
        make cfg
        make -C pkg/kamailio src.rpm
        ls -la
        ls -la ${{ github.workspace }}
        set

    - uses: addnab/docker-run-action@v3
      with:
        image: safarov/kamailio-builder:${{ matrix.os }}
        options: -v ${{ github.workspace }}:/usr/src/kamailio
        run: |
          pwd
          ls -la
          uname -a
          ls -l /usr/src/kamailio
          rpmbuild -ra /usr/src/kamailio/kamailio*.rpm